[SHP_CHACHA20_POLY1305]
CONFIDENTIALITY:ChaCha20-Poly1305
INTEGRITY:NULL

[SHP_AES_256_GCM]
CONFIDENTIALITY:AES/GCM/NoPadding
INTEGRITY:NULL

[SHP_AES_256_CBC_HMAC_SHA256]
CONFIDENTIALITY:AES/CBC/NoPadding
INTEGRITY:MAC
MAC:HmacSHA256
