[SHP_AES_256_CTR_HMAC_SHA512]
CONFIDENTIALITY:AES/CTR/NoPadding
INTEGRITY:MAC
MAC:HmacSHA512

[SHP_CHACHA20_POLY1305]
CONFIDENTIALITY:ChaCha20-Poly1305
INTEGRITY:NULL

[SHP_AES_256_GCM]
CONFIDENTIALITY:AES/GCM/NoPadding
INTEGRITY:NULL

[SHP_AES_256_CTR_HMAC_SHA512]
CONFIDENTIALITY:AES/CTR/NoPadding
INTEGRITY:MAC
MAC:HmacSHA512
