movies.dir:movies

shp.keystore:local/shp-stores/server-keystore.p12
shp.truststore:local/shp-stores/server-truststore.p12
shp.password:changeit

pq.keystore:local/pq-shp-stores/server-keystore.p12
pq.truststore:local/pq-shp-stores/server-truststore.p12
pq.password:changeit
