[SHP_CHACHA20_POLY1305]
CONFIDENTIALITY:ChaCha20-Poly1305

[SHP_DPRG_HMAC_SHA256]
CONFIDENTIALITY:DPRG
INTEGRITY:MAC
MAC:HmacSHA256

[SHP_AES_256_CBC_HMAC_SHA256]
CONFIDENTIALITY:AES/CBC/PKCS5Padding
INTEGRITY:MAC
MAC:HmacSHA256

[SHP_CHACHA20_HMAC_SHA256]
CONFIDENTIALITY:ChaCha20
INTEGRITY:MAC
MAC:HmacSHA256

[SHP_AES_256_GCM]
CONFIDENTIALITY: AES/GCM/NoPadding

[SHP_AES_256_CTR_HMAC_SHA512]
CONFIDENTIALITY:AES/CTR/NoPadding
INTEGRITY:MAC
MAC:HmacSHA512
