# Proxy network configuration
# Cryptographic configuration is in proxy/crypto.properties

# remote: the endpoint from which the proxy receives the stream
# localdelivery: comma-separated list of endpoints to forward the stream to
#                (VLC: udp://@localhost:7777, MPV: udp://localhost:7777)
remote:localhost:8888
localdelivery:localhost:7777
