//remote: the endpoint from which the proxy receives the stream
//localdelivery: the localendpoint where the proxy delivers te stream
//               for playing purpose (ex., VLC or MPV players probably work)
remote:localhost:8888
localdelivery:localhost:7777






